backend:
  name: github
  repo: Plueres/Plueres.github.io
  branch: main

media_folder: "assets/images/uploads"

collections:
  - name: "data"
    label: "Data"
    files:
      - name: "lists"
        label: "Lists"
        file: "_data/lists.yml"
        fields:
          - name: "movies"
            label: "Movies"
            widget: "list"
            collapsed: true
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Tags", name: "tags", widget: "string", required: false}
              - {label: "Watched", name: "watched", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Personal_Rating", name: "personal_rating", widget: "number", required: false}
              - {label: "Review", name: "review", widget: "text", required: false}
          - name: "shows"
            label: "Shows"
            widget: "list"
            collapsed: true
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Tags", name: "tags", widget: "string", required: false}
              - {label: "Watched", name: "watched", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Personal_Rating", name: "personal_rating", widget: "number", required: false}
              - {label: "Review", name: "review", widget: "text", required: false}
          - name: "games"
            label: "Games"
            widget: "list"
            collapsed: true
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Tags", name: "tags", widget: "string", required: false}
              - {label: "Played", name: "played", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Finished", name: "finished", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Personal_Rating", name: "personal_rating", widget: "number", required: false}
              - {label: "Review", name: "review", widget: "text", required: false}
          - name: "wishlists"
            label: "Wishlists"
            widget: "list"
            collapsed: true
            fields:
              - {label: "Name", name: "name", widget: "string", required: false}
              - {label: "Image", name: "image", widget: "link", required: false}
              - {label: "Links", name: "links", widget: "list", fields: [{label: "Link", name: "link", widget: "string"}]}