backend:
  name: github
  repo: Plueres/Plueres.github.io
  branch: main

media_folder: "assets/images/uploads"

collections:
  - name: "movies"
    label: "Movies"
    file: "_data/movieslist.yml"
    fields:
      - label: "List"
        name: "list"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Tags", name: "tags", widget: "string"}
          - {label: "Watched", name: "watched", widget: "boolean", default: false}
          - {label: "Personal Rating", name: "rating", widget: "number"}
          - {label: "Review", name: "review", widget: "text"}
  - name: "shows"
    label: "Shows"
    file: "_data/showslist.yml"
    fields:
      - label: "List"
        name: "list"
        widget: "list"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Tags", name: "tags", widget: "string"}
          - {label: "Watched", name: "watched", widget: "boolean", default: false}
          - {label: "Rating", name: "rating", widget: "number"}
          - {label: "Review", name: "review", widget: "text"}