backend:
  name: github
  repo: Plueres/Plueres.github.io
  branch: main

media_folder: "assets/images/uploads"

collections:
  - name: "movies"
    label: "Movies"
    label_singular: "Movie"  # The label for each item in the list
    file: "_data/movieslist.yml"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Watched", name: "watched", widget: "boolean", default: false}
      - {label: "Personal Rating", name: "rating", widget: "number"}
      - {label: "Review", name: "review", widget: "text"}
  - name: "shows"
    label: "Shows"
    label_singular: "Show"  # The label for each item in the list
    file: "_data/showslist.yml"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Watched", name: "watched", widget: "boolean", default: false}
      - {label: "Rating", name: "rating", widget: "number"}
      - {label: "Review", name: "review", widget: "text"}