backend:
  name: github
  repo: Plueres/Plueres.github.io  # Replace this with your repo's info
  branch: main  # Branch to update (optional; defaults to master)

media_folder: "assets/images/uploads"  # Media files will be stored in the repo under img/uploads

collections:
  - name: "movies"  # Used in routes, e.g., /admin/collections/movies
    label: "Movies"  # Used in the UI
    folder: "_movies"  # The path to the folder where the documents are stored
    create: true  # Allow users to create new documents in this collection
    fields:  # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Tags", name: "tags", widget: "string"}
      - {label: "Watched", name: "watched", widget: "boolean", default: false}
      - {label: "Rating", name: "rating", widget: "number"}
      - {label: "Review", name: "review", widget: "text"}