backend:
  name: github
  repo: Plueres/Plueres.github.io
  branch: main

media_folder: "assets/images/uploads"

collections:
  - name: "data"
    label: "Data"
    files:
      - name: "movies"
        label: "Movies"
        file: "_data/movieslist.yml"
        fields:
          - label: "Movies"
            name: "movies"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Tags", name: "tags", widget: "string"}
              - {label: "Watched", name: "watched", widget: "boolean", default: "!no"}
              - {label: "Personal_Rating", name: "rating", widget: "number"}
              - {label: "Review", name: "review", widget: "text"}
      - name: "shows"
        label: "Shows"
        file: "_data/showslist.yml"
        fields:
          - label: "Shows"
            name: "shows"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Tags", name: "tags", widget: "string"}
              - label: "Watched"
                name: "watched"
                widget: "select"
                options: ["!yes", "!no", "!notsure"]
                default: "!no"
              - {label: "Personal_Rating", name: "rating", widget: "number"}
              - {label: