backend:
  name: github
  repo: Plueres/Plueres.github.io
  branch: main

media_folder: "assets/images/uploads"

collections:
  - name: "content"
    label: "Content"
    files:
      - name: "movies"
        label: "Movies"
        file: "movielist.md"
        fields:
          - label: "Movies"
            name: "movies"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Tags", name: "tags", widget: "string"}
              - {label: "Watched", name: "watched", widget: "boolean", default: false}
              - {label: "Personal Rating", name: "rating", widget: "number"}
              - {label: "Review", name: "review", widget: "text"}
      - name: "shows"
        label: "Shows"
        file: "showlist.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Tags", name: "tags", widget: "string"}
          - {label: "Watched", name: "watched", widget: "boolean", default: false}
          - {label: "Rating", name: "rating", widget: "number"}
          - {label: "Review", name: "review", widget: "text"}