backend:
  name: github
  repo: Plueres/Plueres.github.io
  branch: main

media_folder: "assets/images/uploads"

collections:
  - name: "data"
    label: "Data"
    sortableFields: ['title']
    files:
      - name: "movies"
        label: "Movies"
        file: "_data/movies.yml"
        fields:
          - label: "Movies"
            name: "movies"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Tags", name: "tags", widget: "string", required: false}
              - {label: "Watched", name: "watched", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Personal_Rating", name: "personal_rating", widget: "number", required: false}
              - {label: "Review", name: "review", widget: "text", required: false}
      - name: "shows"
        label: "Shows"
        file: "_data/shows.yml"
        fields:
          - label: "Shows"
            name: "shows"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Tags", name: "tags", widget: "string", required: false}
              - {label: "Watched", name: "watched", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Personal_Rating", name: "personal_rating", widget: "number", required: false}
              - {label: "Review", name: "review", widget: "text", required: false}
      - name: "games"
        label: "Games"
        file: "_data/games.yml"
        fields:
          - label: "Games"
            name: "games"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Tags", name: "tags", widget: "string", required: false}
              - {label: "Played", name: "played", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Finished", name: "finished", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Personal_Rating", name: "personal_rating", widget: "number", required: false}
              - {label: "Review", name: "review", widget: "text", required: false}