backend:
  name: github
  repo: Plueres/Plueres.github.io
  branch: main

media_folder: "assets/images/uploads"

collections:
  - name: "lists"
    label: "Lists"
    files:
      - name: "movies"
        label: "Movies"
        file: "_data/lists.yml"
        fields:
          - label: "Movie"
            name: "movie"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Tags", name: "tags", widget: "string", required: false}
              - {label: "Watched", name: "watched", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Personal_Rating", name: "personal_rating", widget: "number", required: false}
              - {label: "Review", name: "review", widget: "text", required: false}
          - label: "Show"
            name: "show"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Tags", name: "tags", widget: "string", required: false}
              - {label: "Watched", name: "watched", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Personal_Rating", name: "personal_rating", widget: "number", required: false}
              - {label: "Review", name: "review", widget: "text", required: false}
          - label: "Game"
            name: "game"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Tags", name: "tags", widget: "string", required: false}
              - {label: "Played", name: "played", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Finished", name: "finished", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Personal_Rating", name: "personal_rating", widget: "number", required: false}
              - {label: "Review", name: "review", widget: "text", required: false}