backend:
  name: github
  repo: Plueres/Plueres.github.io
  branch: main

media_folder: "assets/images"

collections:
  - name: "articles"
    label: "Articles"
    folder: "_articles"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "select", default: "article", options: ["article", "minecraftpost"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", default: ""}
      - {label: "Header Image", name: "header_image", widget: "image"}
      - {label: "Images", name: "images", widget: "list", fields: [{label: "Image", name: "", widget: "image"}], required: false}
      - {label: "Tags", name: "tags", widget: "string", default: "[]", hint: "Enter tags in the format [tag1, tag2, tag3]", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: false}
  - name: "lists"
    label: "Lists"
    files:
      - name: "movies"
        label: "Movies"
        file: "_data/movies.yml"
        collapsed: true
        fields:
          - label: "Movies"
            name: "movies"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Tags", name: "tags", widget: "string", required: false}
              - {label: "Watched", name: "watched", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Personal_Rating", name: "personal_rating", widget: "number", required: false}
              - {label: "Review", name: "review", widget: "text", required: false}
      - name: "shows"
        label: "Shows"
        file: "_data/shows.yml"
        collapsed: true
        fields:
          - label: "Shows"
            name: "shows"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Tags", name: "tags", widget: "string", required: false}
              - {label: "Season", name: "season", widget: "string", required: false}
              - {label: "Watched", name: "watched", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Personal_Rating", name: "personal_rating", widget: "number", required: false}
              - {label: "Review", name: "review", widget: "text", required: false}
      - name: "games"
        label: "Games"
        file: "_data/games.yml"
        collapsed: true
        fields:
          - label: "Games"
            name: "games"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Tags", name: "tags", widget: "string", required: false}
              - {label: "Played", name: "played", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Finished", name: "finished", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Personal_Rating", name: "personal_rating", widget: "number", required: false}
              - {label: "Review", name: "review", widget: "text", required: false}
      - name: "wishlist"
        label: "Wishlist"
        file: "_data/wishlists.yml"
        fields:
          - name: "wishlist"
            label: "Wishlist"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string", required: false}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Links", name: "links", widget: "list", fields: [{label: "Name", name: "name", widget: "string"}, {label: "URL", name: "url", widget: "string"}]}
          - name: "christmaslist"
            label: "Christmas List"
            widget: "list"
            fields:
              - {label: "Name", name: "name", widget: "string", required: false}
              - {label: "Image", name: "image", widget: "image", required: false}
              - {label: "Description", name: "description", widget: "string", required: false}
              - {label: "Links", name: "links", widget: "list", fields: [{label: "Name", name: "name", widget: "string"}, {label: "URL", name: "url", widget: "string"}]}