backend:
  name: github
  repo: Plueres/Plueres.github.io
  branch: main

media_folder: "assets/images/uploads"

collections:
  - name: "lists"
    label: "Lists"
    files:
      - name: "movies"
        label: "Movies"
        file: "_data/movies.yml"
        collapsed: true
        fields:
          - label: "Movies"
            name: "movies"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Tags", name: "tags", widget: "string", required: false}
              - {label: "Watched", name: "watched", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Personal_Rating", name: "personal_rating", widget: "number", required: false}
              - {label: "Review", name: "review", widget: "text", required: false}
      - name: "shows"
        label: "Shows"
        file: "_data/shows.yml"
        collapsed: true
        fields:
          - label: "Shows"
            name: "shows"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Tags", name: "tags", widget: "string", required: false}
              - {label: "Watched", name: "watched", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Personal_Rating", name: "personal_rating", widget: "number", required: false}
              - {label: "Review", name: "review", widget: "text", required: false}
      - name: "games"
        label: "Games"
        file: "_data/games.yml"
        collapsed: true
        fields:
          - label: "Games"
            name: "games"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string", required: false}
              - {label: "Tags", name: "tags", widget: "string", required: false}
              - {label: "Played", name: "played", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Finished", name: "finished", widget: "select", options: ["!yes", "!no", "!notsure"], default: "!no", required: false}
              - {label: "Personal_Rating", name: "personal_rating", widget: "number", required: false}
              - {label: "Review", name: "review", widget: "text", required: false}
      - name: "wishlist"
        label: "Wishlist"
        file: "_data/wishlists.yml"
        fields:
          - name: "wishlist"
            label: "Wishlist"
            widget: "object"
            fields:
              - label: "List items"
                name: "list item"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string", required: false}
                  - {label: "Image", name: "image", widget: "image", required: false}
                  - {label: "Links", name: "links", widget: "list", fields: [{label: "Name", name: "name", widget: "string"}, {label: "URL", name: "url", widget: "string"}]}
          - name: "christmaslist"
            label: "Christmas List"
            widget: "object"
            fields:
              - label: "List Items"
                name: "list items"
                widget: "list"
                fields:
                  - {label: "Name", name: "name", widget: "string", required: false}
                  - {label: "Image", name: "image", widget: "image", required: false}
                  - {label: "Description", name: "description", widget: "string", required: false}
                  - {label: "Links", name: "links", widget: "list", fields: [{label: "Name", name: "name", widget: "string"}, {label: "URL", name: "url", widget: "string"}]}