backend:
  name: github
  repo: Plueres/Plueres.github.io
  branch: main

media_folder: "assets/images/uploads"

collections:
  - name: "movies"
    label: "Movies"
    file: "_movies/movielist.md"
    fields:
      - label: "Movies"
        name: "movies"
        widget: "list"
        fields:
          - {label: "Row", name: "row", widget: "list", fields: [
              {label: "Column", name: "column", widget: "string"}
            ]}